language: python
dist: xenial
python:
  - "3.7"

before_install:
  - pip install poetry

install:
  - poetry install -v
  - pip install tox-travis

script:
  - tox

before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
  - poetry build

deploy:
  provider: script
  script: poetry publish --build
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"

env:
  global:
  - secure: 
  - secure: 
